README.md, custom_components/omnik_inverter/sensor.py
This PR adds support for inverters that output a `myDeviceArray` instead of `webData`.
=> Add support for myDeviceArray

custom_components/omnik_inverter/sensor.py
Change the unit of measurement for `powercurrent` from `Watt` to `W` as per default in HA -> https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/const.py#L336
Use the const from HA for the units
=> Change Watt to W and use HA const

custom_components/omnik_inverter/sensor.py
I run some checks on the code in Visual Studio (Python checks and black) and found some cleanup items
- Changed `RunTimeError` to `RuntimeError`
- Some docstrings were actually comments so changed them
- Unused variable `e` removed
- Some other cleanup
=> Some code cleanup

custom_components/omnik_inverter/sensor.py
Add unique_id so name and entity-id can be changed from the front-end
=> Add unique_id

custom_components/omnik_inverter/sensor.py
Guess this is a bit cleaner and avoids the return
=> Some changes to #8

custom_components/omnik_inverter/sensor.py
This extends the caching system with 2 new cases, making it a total of 4 cases.
Basically it:
- Updates the cache if the current value is bigger or equal to the cache value
- Use the cache value if the current value is smaller (for example when your inverter resets to early)
- If the day has passed and the current value is equal to the cached value (if your inverter did not reset yet), then output 0
- If the day has passed and the current value is no longer equal to the cached value, use the currentValue and update the cacheDay
I'll run it overnight and see if it works as expected :-)
=> Use day instead of time for caching

README.md
Update the HACS installation instructions.
=> Update HACS installation instructions

custom_components/omnik_inverter/sensor.py
=> Update "update time" to 5 minutes instead of 500s

README.md, custom_components/omnik_inverter/sensor.py
Add a `scan_interval` configuration option to configure the time between updates
Closes #21
=> Make scan_interval configurable

custom_components/omnik_inverter/manifest.json, custom_components/omnik_inverter/sensor.py
[Compare v1.5.0 - v1.5.1](https://github.com/robbinjanssen/home-assistant-omnik-inverter/compare/v1.5.0...v1.5.1)
- Version info to `manifest.json`.
=> Add version to manifest

.github/dependabot.yml, .github/labels.yml, .github/release-drafter.yml, .github/workflows/codeql.yaml, .github/workflows/draft-release.yaml, .github/workflows/labels.yaml, .github/workflows/pr-labels.yaml
**This PR will do:**
- Add more labels and check on use in the PR's
- Add the release drafter
- Add depencies checks with dependabot
- Scan the code on quality with CodeQL
=> 🔨  Improve the repo workflow

.github/dependabot.yml, .github/labels.yml, .github/release-drafter.yml, .github/workflows/codeql.yaml, .github/workflows/draft-release.yaml, .github/workflows/labels.yaml, .github/workflows/pr-labels.yaml
Reverts robbinjanssen/home-assistant-omnik-inverter#47
Turns out the revert wasn't a good move lol
=> Revert "Revert "🔨  Improve the repo workflow""

custom_components/omnik_inverter/__init__.py, custom_components/omnik_inverter/config_flow.py, custom_components/omnik_inverter/const.py, custom_components/omnik_inverter/strings.json, custom_components/omnik_inverter/translations/en.json, custom_components/omnik_inverter/translations/nl.json
- Add scan interval to the options flow
- Remove use JSON option from the options flow and change text
=> Improve the config flow

custom_components/omnik_inverter/manifest.json
Bump the python package to the latest version
=> ⬆️ Bump the python package version to 0.5.0

README.md, custom_components/omnik_inverter/__init__.py, custom_components/omnik_inverter/config_flow.py, custom_components/omnik_inverter/const.py, custom_components/omnik_inverter/strings.json, custom_components/omnik_inverter/translations/en.json, custom_components/omnik_inverter/translations/nl.json
- ✨ Add support for HTML source inverters
- 📓 Update the strings of the integration
- 📚 Update the documentation
close #45
=> Add support for HTML sources

custom_components/omnik_inverter/manifest.json
Bump to the latest version, with with merging until the other is merged 😉
=> Bump the python package version

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, README.md
- 📓 Update the README
- 🎉 Add CODE_OF_CONDUCT and CONTRIBUTION guides
=> Update documentation for HTML support

custom_components/omnik_inverter/__init__.py, custom_components/omnik_inverter/config_flow.py, custom_components/omnik_inverter/const.py
- 🧰 Add warning when trying to migrate config_flow from previous beta
=> Warn the user when trying to migrate config_flow from previous beta

custom_components/omnik_inverter/manifest.json
=> Bump python package version

.github/ISSUE_TEMPLATE.md
Add an issue template that will stimulate a better issue report. Refers to the newly added [diagnostics feature](https://github.com/robbinjanssen/home-assistant-omnik-inverter/pull/90)
=> Add issue template to repository

README.md
Apparently this inverter also works :-)
See https://github.com/robbinjanssen/home-assistant-omnik-inverter/discussions/94
=> Add Hosola 1500TL to supported models

README.md
The [Sofar 3600LTM](https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/104) seems to work with this integration as well :-)
=> Add Sofar 3600LTM to the supported models

README.md
See https://github.com/robbinjanssen/home-assistant-omnik-inverter/discussions/94#discussioncomment-2587816
=> Add Huayu HY-600-Pro to the supported models

README.md
Works great with my Bosswerk BW-MI300 inverter.
=> Add BW-MI300 to supported models

custom_components/omnik_inverter/translations/de.json
=> add German translation
